/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_home_core_ScreenPowerSwitcher */

#ifndef _Included_by_home_core_ScreenPowerSwitcher
#define _Included_by_home_core_ScreenPowerSwitcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_home_core_ScreenPowerSwitcher
 * Method:    switchOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_home_core_ScreenPowerSwitcher_switchOn
  (JNIEnv *, jobject);

/*
 * Class:     by_home_core_ScreenPowerSwitcher
 * Method:    switchOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_home_core_ScreenPowerSwitcher_switchOff
  (JNIEnv *, jobject);

/*
 * Class:     by_home_core_ScreenPowerSwitcher
 * Method:    lowPower
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_home_core_ScreenPowerSwitcher_lowPower
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
