/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_home_core_WorkstationLocker */

#ifndef _Included_by_home_core_WorkstationLocker
#define _Included_by_home_core_WorkstationLocker
#define _WIN32_WINNT 0x0500
#define WINVER 0x0500
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_home_core_WorkstationLocker
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_home_core_WorkstationLocker_lock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
